config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root  "products#index"
  resources :buys 

  resources :products do 
    member do 
      get 'select_buy', to: 'buys#select_buy'
    end  
  end  

  resources :clients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buy.rb
class Buy < ApplicationRecord
  belongs_to :client
  belongs_to :product
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :buy
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :buy
    validates :description, presence: {message:"A Descrição é um campo obrigatório"} 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  def index
    @buys = Buy.all
  end
  def new 
    @product = Product.find(params[:product_id])
  end  
  def create 
  end  
  def save
  
  end 
  def select_buy
    @product = Product.find(params[:id])
    @clients = Client.all
  end  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end
  def new 
    @client = Client.new()

  end 
  def edit 
    @client = Client.find(params[:id])
  end  
  def update 
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path 
    else 
      render :edit, status: :unprocessable_entity
    end  
  end  
  def create 
    @client = Client.new(client_params)

    if @client.save
      redirect_to clients_path
    else
      render :new, status: :unprocessable_entity
    end  
  end
  def destroy 
    @client = Client.find(params[:id])
    @client.destroy

    redirect_to clients_path
  end  
  private 
  def client_params 
    params.require(:client).permit(:name, :city, :district, :cpf)
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def new 
    @product  = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end 
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end  
  def edit 
    @product = Product.find(params[:id])
  end  
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params) 
       redirect_to products_path
    else
      render :edit, status: :unprocessable_entity
    end

  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/buys/index.html.erb
<h1>Buys#index</h1>
<p>Find me in app/views/buys/index.html.erb</p>

app/views/buys/select_buy.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path %>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white">Adicionar</a>
           <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
       <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>
      </nav>

      
 <div class="content  pt-5">
   
    <div class="container-fluid">
    <h4>Venda do Produto - <%=@product.name%> </h4>
        <div class="row">
            <div class="col-12 table-responsive">
                <table class="table">
                    <thead class="thead-dark"> 
                      <tr>
                        <th >ID</th>
                        <th >Nome</th>
                        <th >CPF</th>
                        <th >Cidade</th>
                        <th>Bairro</th>
                        <th>Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @clients.each do |client| %>
                     <tr>
                        <th scope=""><%= client.id%></th>
                        <td><%= client.name %> </td>
                        <td><%= client.cpf %> </td>
                        <td><%= client.city %> </td>
                        <td><%= client.district %> </td>
                           <td  class="d-flex"><%= link_to edit_product_path(client), class: "pr-2" do %>
  <button type="button" class="btn btn-primary text-white">Selecionar</button>
 <% end %> 
    
  </td>

                     </tr>

                    <%end%>
                    </tbody>
                   
                  </table> 
                    <% if @clients.empty? %>
                        <h5 class="text-center"> Não Há clientes Cadastrados!!</h4>
                    <% end %>
            </div>
            
        </div>
    </div>
   
 </div>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/clients/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path%>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white" >Adicionar</a>
         <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
          <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>

      </nav>
     
    <div class="container pt-5"> 
        <h3>Cadastro de Cliente</h3>
        <%= form_with url: client_path(@client), model:  @client do |form| %>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                 <%= form.text_field :name, class: "form-control", placeholder: "Nome" %>
             
              </div>
              <div class="form-group col-md-6">
                <label for="cpf">CPF</label>
                  <%= form.text_field :cpf, class:"form-control", placeholder:"CPF" %>  
                </div>
            </div>
            <div class="form-group">
              <label for="cidade">Cidade</label>
             <%= form.text_field :city, class:"form-control", placeholder:"Cidade" %>  
              
              </div>
            <div class="form-group">
              <label for="bairro">Bairro</label>
             <%= form.text_field :district, class:"form-control", placeholder:"Bairro" %>  

            </div>
        
         
            <%= form.submit "Editar", class: "btn btn-info"%>
          <%end%>
    </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path %>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white">Adicionar</a>
           <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
       <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>
      </nav>

      
 <div class="content  pt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 table-responsive">
                <table class="table">
                    <thead class="thead-dark"> 
                      <tr>
                        <th >ID</th>
                        <th >Nome</th>
                        <th >CPF</th>
                        <th >Cidade</th>
                        <th>Bairro</th>
                        <th>Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @clients.each do |client| %>
                     <tr>
                        <th scope=""><%= client.id%></th>
                        <td><%= client.name %> </td>
                        <td><%= client.cpf %> </td>
                        <td><%= client.city %> </td>
                        <td><%= client.district %> </td>
                           <td  class="d-flex"><%= link_to edit_client_path(client), class: "pr-2" do %>
  <button type="button" class="btn btn-primary text-white">Editar</button>
<% end %>   <%= form_with(model: client, local: true, method: :delete, data: { confirm: 'Tem certeza?' }) do |form| %>
    <%= form.submit "Excluir", class: "btn btn-danger" %>


  <% end %>
    
  </td>

                     </tr>

                    <%end%>
                    </tbody>
                   
                  </table> 
                    <% if @clients.empty? %>
                        <h5 class="text-center"> Não Há clientes Cadastrados!!</h4>
                    <% end %>
            </div>
            
        </div>
    </div>
   
 </div>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/clients/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path%>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white" >Adicionar</a>
         <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
          <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>

      </nav>
     
    <div class="container pt-5"> 
        <h3>Cadastro de Cliente</h3>
        <%= form_with model: @client do |form| %>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                 <%= form.text_field :name, class: "form-control", placeholder: "Nome" %>
             
              </div>
              <div class="form-group col-md-6">
                <label for="cpf">CPF</label>
                  <%= form.text_field :cpf, class:"form-control", placeholder:"CPF" %>  
                </div>
            </div>
            <div class="form-group">
              <label for="cidade">Cidade</label>
             <%= form.text_field :city, class:"form-control", placeholder:"Cidade" %>  
              
              </div>
            <div class="form-group">
              <label for="bairro">Bairro</label>
             <%= form.text_field :district, class:"form-control", placeholder:"Bairro" %>  

            </div>
        
         
            <%= form.submit "Cadastrar", class: "btn btn-info"%>
          <%end%>
    </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estoque</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
 <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path %>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white">Adicionar</a>
           <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
       <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>
      </nav>

     
    <div class="container pt-5"> 
        <h3>Editar Produto</h3>
        <%= form_with model: @product, url: product_path(@product), method: :patch do |form| %>
      
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                 <%= form.text_field :name, class: "form-control", placeholder: "Nome do Produto" %>
                <% @product.errors.full_messages_for(:name).each do |message|%>
                    <div class="text-danger"><%= message.gsub('Name', '')%></div>
                <%end%>
              </div>
              <div class="form-group col-md-6">
                <label for="preco">Preço</label>
                  <%= form.number_field :price, class:"form-control", placeholder:"Preço" %>  
                </div>
            </div>
            <div class="form-group">
              <label for="descricao">Descrição</label>
             <%= form.text_field :description, class:"form-control", placeholder:"Descrição" %>  
                <%@product.errors.full_messages_for(:description).each do |message|%>
                    <div class="text-danger"><%=message.gsub('Description', '')%> </div>
                <%end%>
              </div>
            <div class="form-group">
              <label for="quantidade">Quantidade</label>
             <%= form.number_field :amount, class:"form-control", placeholder:"Descrição" %>  

            </div>
        
         
            <%= form.submit "Editar", class: "btn btn-info"%>
          <%end%>
    </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path %>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white">Adicionar</a>
           <a class="nav-link text-white " href="<%= clients_path %>">Listar Clientes</a>
       <a href="<%= new_client_path %>" class="nav-link text-white">Adicionar Cliente</a>
      </nav>

      
 <div class="content  pt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 table-responsive">
                <table class="table">
                    <thead class="thead-dark"> 
                      <tr>
                        <th >ID</th>
                        <th >Nome</th>
                        <th >Descricao</th>
                        <th >Quantidade</th>
                        <th>Preço</th>
                        <th>Ações</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @products.each do |product| %>
                        <tr>
                        <th scope=""><%= product.id%></th>
                        <td><%= product.name %></td>
                        <td><%= product.description %></td>
                        <td><%= product.amount %></td>
                        <td>R$ <%= product.price.to_s.gsub('.', ',') %>0</td>
                        <td  class="d-flex"><%= link_to edit_product_path(product), class: "pr-2" do %>
  <button type="button" class="btn btn-primary text-white">Editar</button>
<% end %>   <%= form_with(model: product, local: true, method: :delete, data: { confirm: 'Tem certeza?' }) do |form| %>
    <%= form.submit "Excluir", class: "btn btn-danger" %>
  <% end %>
  <div class="pl-2">
  
      <%= link_to "Comprar", select_buy_product_path(product), class: "btn btn-primary " %>
  </div>
  </td>
                      </tr>
                     <% end %> 
                    </tbody>
                   
                  </table> 
                    <% if @products.empty? %>
                        <h5 class="text-center"> Não Há Produtos Cadastrados!!</h4>
                    <% end %>
            </div>
            
        </div>
    </div>
   
 </div>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/products/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="nav  bg-info  p-2">
        <a class="nav-link text-white " href="<%= products_path%>">Listar</a>
        <a href="<%= new_product_path %>" class="nav-link text-white" >Adicionar</a>
      </nav>
     
    <div class="container pt-5"> 
        <h3>Cadastro Produto</h3>
        <%= form_with model: @product do |form| %>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="nome">Nome</label>
                 <%= form.text_field :name, class: "form-control", placeholder: "Nome do Produto" %>
                <% @product.errors.full_messages_for(:name).each do |message|%>
                    <div class="text-danger"><%= message.gsub('Name', '')%></div>
                <%end%>
              </div>
              <div class="form-group col-md-6">
                <label for="preco">Preço</label>
                  <%= form.number_field :price, class:"form-control", placeholder:"Preço" %>  
                </div>
            </div>
            <div class="form-group">
              <label for="descricao">Descrição</label>
             <%= form.text_field :description, class:"form-control", placeholder:"Descrição" %>  
                <%@product.errors.full_messages_for(:description).each do |message|%>
                    <div class="text-danger"><%=message.gsub('Description', '')%> </div>
                <%end%>
              </div>
            <div class="form-group">
              <label for="quantidade">Quantidade</label>
             <%= form.number_field :amount, class:"form-control", placeholder:"Descrição" %>  

            </div>
        
         
            <%= form.submit "Cadastrar", class: "btn btn-info"%>
          <%end%>
    </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>